import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarMenu from "./components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Hunt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavbarMenu />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
